-
  name: 'Psmb.FlatNav'
  uriPattern: 'flatnav/{@action}'
  defaults:
    '@package':    'Psmb.FlatNav'
    '@controller': 'Standard'
    '@format':     'html'
    '@action':     'query'
  appendExceedingArguments: TRUE
